export const SET_BUN = "SET_BUN"
export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"
export const REMOVE_ALL_INGREDIENTS = "REMOVE_ALL_INGREDIENTS"
export const CHANGE_INGREDIENTS_ORDER = "CHANGE_INGREDIENTS_ORDER"

